### PR TITLE
Implement SetTorrentOptions method

### PR DESCRIPTION
**Pull request by ailox**
This pull request implements the `core.set_torrent_options` rpc method.

### CODE REVIEW

**Comment by ailox** [comment]
This was tested with deluge 2.0.3. As a crude test one could use something like:

```go
	c.SetTorrentOptions(
		"86d4c80024a469be4c50bc5a102cf71780310074",
		delugeclient.Options{
			"shared":                       true,
			"prioritize_first_last_pieces": false,
			"sequential_download":          true,
			"stop_ratio":                   13.37,
		},
	)
```

I wanted to add the magic strings for the keys as constants, but the supported attributes are different between the versions. If both daemon versions should still be supported, This should be part of a seperate change.

**Comment by gdm85** [comment]
@ailox you did well, but now I realise that a [commit I previously cherry-picked](https://github.com/gdm85/go-libdeluge/commit/ac3c8a60acf43c7e85cb7976e5fc8686c6ed63ae) did not implement the `Options` in an idiomatic Go way, and it shows up in the current situation where we want support of both v1 and v2.

I will merge this PR and then come up with a way to remove the `interface{}` map which is too lax and at the same time try to tackle v1/v2 support.

**Comment by gdm85** [comment]
@ailox I have implemented what I had in mind in e1f610e395279d1ccc6db720efb1b06d875579b6

However I am not sure whether "setting all fields with a default value" (new behaviour) vs "setting only specific fields" (previous behaviour) is equivalent, needs more testing.

**Comment by gdm85** [comment]
> In theory this seemed like a good idea, but now I have some doubts.
> The old way of specifying options was via the key-value pairs in a hashmap. This means that options could stay 'untouched' in their default value, if they were not defined.
> 
> With this struct layout, every value has to be explicitly defined, otherwise its Null value will overwrite the default value every time. (e.g. '0' for connections and speed settings).
> 
> A way to work around this would be using pointers, and checking for nil. But this seems pretty complicated (initializing a string pointer is a small PITA).

@ailox yes, I mentioned this in above comment. At this point I wonder:
* what will the Go default values do on deluge daemon side? Can we set the proper deluge default values (`-1` etc) on Go side? (ugly, because deluge daemon might change them, but would work)

I am not in favour of a map of `interface{}` values as it was done before so it's either that or the `nil` pointer approach.

A third way would be to compare with `reflect.Zero()` and skip those, but it would disallow the user to set those values explicitly, so also not a nice solution.

Interestingly, the deprecated APIs would not pose such initialisation problems.

**Pull request merged**
